source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise', '~> 3.4.1'
gem 'paperclip', '~> 4.2.1'
gem 'simple_form', '~> 3.1.0'
gem 'acts_as_votable', '~> 0.10.0'
gem 'rails_12factor', '~> 0.0.3'
gem 'pry-rails', '~> 0.3.3'
gem 'metainspector'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'bootsy', '~> 2.0.13'
gem 'jcrop-rails-v2', '~> 0.9.12.3'
gem 'papercrop', '~> 0.2.0'